      PROGRAM CALCPI
      IMPLICIT NONE
      REAL*8 :: A,B,PI
      INTEGER :: N
      A = 0.0   !DEFINE INTERVAL START
      B = 1.0   !DEFINE INTERVAL STOP
      !READ THE NUMBER OF SUB-INTERVALS
      PRINT *,'INPUT THE NUMBER OF SUB-INTERVALS'
      READ(*,*) N
        CALL TRAP(A,B,N,PI)
        PRINT *,'PI = ',PI
      STOP
      END
